version: '3'
services:
  rabbitmq-server:
    image: openjob:v1.0.0
    restart: always
    container_name: openjob-server
    environment:
      - OJ_DS_URL=jdbc:mysql://192.168.31.136:3306/openjob?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      - OJ_LOG_STORAGE_MYSQL_URL=jdbc:mysql://192.168.31.136:3306/openjob?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    ports:
      - "8080:8080"